(cl:defpackage dmp-srv
  (:use )
  (:export
   "GETDMPPLAN"
   "<GETDMPPLAN-REQUEST>"
   "GETDMPPLAN-REQUEST"
   "<GETDMPPLAN-RESPONSE>"
   "GETDMPPLAN-RESPONSE"
   "LEARNDMPFROMDEMO"
   "<LEARNDMPFROMDEMO-REQUEST>"
   "LEARNDMPFROMDEMO-REQUEST"
   "<LEARNDMPFROMDEMO-RESPONSE>"
   "LEARNDMPFROMDEMO-RESPONSE"
   "SETACTIVEDMP"
   "<SETACTIVEDMP-REQUEST>"
   "SETACTIVEDMP-REQUEST"
   "<SETACTIVEDMP-RESPONSE>"
   "SETACTIVEDMP-RESPONSE"
  ))

