// Generated by gencpp from file dmp/LearnDMPFromDemoRequest.msg
// DO NOT EDIT!


#ifndef DMP_MESSAGE_LEARNDMPFROMDEMOREQUEST_H
#define DMP_MESSAGE_LEARNDMPFROMDEMOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dmp/DMPTraj.h>

namespace dmp
{
template <class ContainerAllocator>
struct LearnDMPFromDemoRequest_
{
  typedef LearnDMPFromDemoRequest_<ContainerAllocator> Type;

  LearnDMPFromDemoRequest_()
    : demo()
    , k_gains()
    , d_gains()
    , num_bases(0)  {
    }
  LearnDMPFromDemoRequest_(const ContainerAllocator& _alloc)
    : demo(_alloc)
    , k_gains(_alloc)
    , d_gains(_alloc)
    , num_bases(0)  {
  (void)_alloc;
    }



   typedef  ::dmp::DMPTraj_<ContainerAllocator>  _demo_type;
  _demo_type demo;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _k_gains_type;
  _k_gains_type k_gains;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _d_gains_type;
  _d_gains_type d_gains;

   typedef int32_t _num_bases_type;
  _num_bases_type num_bases;





  typedef boost::shared_ptr< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LearnDMPFromDemoRequest_

typedef ::dmp::LearnDMPFromDemoRequest_<std::allocator<void> > LearnDMPFromDemoRequest;

typedef boost::shared_ptr< ::dmp::LearnDMPFromDemoRequest > LearnDMPFromDemoRequestPtr;
typedef boost::shared_ptr< ::dmp::LearnDMPFromDemoRequest const> LearnDMPFromDemoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dmp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'dmp': ['/home/bhertel/catkin_ws/src/dmp/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7c68a7f789c246aea188ade43175b30";
  }

  static const char* value(const ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7c68a7f789c246aULL;
  static const uint64_t static_value2 = 0xea188ade43175b30ULL;
};

template<class ContainerAllocator>
struct DataType< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dmp/LearnDMPFromDemoRequest";
  }

  static const char* value(const ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
DMPTraj demo\n\
\n\
\n\
float64[] k_gains\n\
float64[] d_gains\n\
\n\
\n\
int32 num_bases\n\
\n\
\n\
================================================================================\n\
MSG: dmp/DMPTraj\n\
# points and times should be the same length\n\
DMPPoint[] points\n\
\n\
# Times of observations, in seconds, starting at zero\n\
float64[] times\n\
\n\
\n\
\n\
================================================================================\n\
MSG: dmp/DMPPoint\n\
# Positions and velocities of DOFs\n\
#Velocity is only used for movement plans, not for giving demonstrations.\n\
float64[] positions\n\
float64[] velocities\n\
\n\
\n\
";
  }

  static const char* value(const ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.demo);
      stream.next(m.k_gains);
      stream.next(m.d_gains);
      stream.next(m.num_bases);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LearnDMPFromDemoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dmp::LearnDMPFromDemoRequest_<ContainerAllocator>& v)
  {
    s << indent << "demo: ";
    s << std::endl;
    Printer< ::dmp::DMPTraj_<ContainerAllocator> >::stream(s, indent + "  ", v.demo);
    s << indent << "k_gains[]" << std::endl;
    for (size_t i = 0; i < v.k_gains.size(); ++i)
    {
      s << indent << "  k_gains[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.k_gains[i]);
    }
    s << indent << "d_gains[]" << std::endl;
    for (size_t i = 0; i < v.d_gains.size(); ++i)
    {
      s << indent << "  d_gains[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.d_gains[i]);
    }
    s << indent << "num_bases: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_bases);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DMP_MESSAGE_LEARNDMPFROMDEMOREQUEST_H
