// Generated by gencpp from file brendan_ur5e/shutdown_requestResponse.msg
// DO NOT EDIT!


#ifndef BRENDAN_UR5E_MESSAGE_SHUTDOWN_REQUESTRESPONSE_H
#define BRENDAN_UR5E_MESSAGE_SHUTDOWN_REQUESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace brendan_ur5e
{
template <class ContainerAllocator>
struct shutdown_requestResponse_
{
  typedef shutdown_requestResponse_<ContainerAllocator> Type;

  shutdown_requestResponse_()
    : b(0)  {
    }
  shutdown_requestResponse_(const ContainerAllocator& _alloc)
    : b(0)  {
  (void)_alloc;
    }



   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct shutdown_requestResponse_

typedef ::brendan_ur5e::shutdown_requestResponse_<std::allocator<void> > shutdown_requestResponse;

typedef boost::shared_ptr< ::brendan_ur5e::shutdown_requestResponse > shutdown_requestResponsePtr;
typedef boost::shared_ptr< ::brendan_ur5e::shutdown_requestResponse const> shutdown_requestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace brendan_ur5e

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5a3c6284d5ab11e232db053f443f102";
  }

  static const char* value(const ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5a3c6284d5ab11eULL;
  static const uint64_t static_value2 = 0x232db053f443f102ULL;
};

template<class ContainerAllocator>
struct DataType< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brendan_ur5e/shutdown_requestResponse";
  }

  static const char* value(const ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 b\n\
\n\
";
  }

  static const char* value(const ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct shutdown_requestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brendan_ur5e::shutdown_requestResponse_<ContainerAllocator>& v)
  {
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRENDAN_UR5E_MESSAGE_SHUTDOWN_REQUESTRESPONSE_H
