// Generated by gencpp from file brendan_ur5e/shutdown_requestRequest.msg
// DO NOT EDIT!


#ifndef BRENDAN_UR5E_MESSAGE_SHUTDOWN_REQUESTREQUEST_H
#define BRENDAN_UR5E_MESSAGE_SHUTDOWN_REQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace brendan_ur5e
{
template <class ContainerAllocator>
struct shutdown_requestRequest_
{
  typedef shutdown_requestRequest_<ContainerAllocator> Type;

  shutdown_requestRequest_()
    : a(0)  {
    }
  shutdown_requestRequest_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct shutdown_requestRequest_

typedef ::brendan_ur5e::shutdown_requestRequest_<std::allocator<void> > shutdown_requestRequest;

typedef boost::shared_ptr< ::brendan_ur5e::shutdown_requestRequest > shutdown_requestRequestPtr;
typedef boost::shared_ptr< ::brendan_ur5e::shutdown_requestRequest const> shutdown_requestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace brendan_ur5e

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "019706110004b728d56d8baaa8e32797";
  }

  static const char* value(const ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x019706110004b728ULL;
  static const uint64_t static_value2 = 0xd56d8baaa8e32797ULL;
};

template<class ContainerAllocator>
struct DataType< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brendan_ur5e/shutdown_requestRequest";
  }

  static const char* value(const ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n\
";
  }

  static const char* value(const ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct shutdown_requestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brendan_ur5e::shutdown_requestRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRENDAN_UR5E_MESSAGE_SHUTDOWN_REQUESTREQUEST_H
