// Generated by gencpp from file brendan_ur5e/shutdown_request.msg
// DO NOT EDIT!


#ifndef BRENDAN_UR5E_MESSAGE_SHUTDOWN_REQUEST_H
#define BRENDAN_UR5E_MESSAGE_SHUTDOWN_REQUEST_H

#include <ros/service_traits.h>


#include <brendan_ur5e/shutdown_requestRequest.h>
#include <brendan_ur5e/shutdown_requestResponse.h>


namespace brendan_ur5e
{

struct shutdown_request
{

typedef shutdown_requestRequest Request;
typedef shutdown_requestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct shutdown_request
} // namespace brendan_ur5e


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::brendan_ur5e::shutdown_request > {
  static const char* value()
  {
    return "f16097f93022db785b2cc9436c158893";
  }

  static const char* value(const ::brendan_ur5e::shutdown_request&) { return value(); }
};

template<>
struct DataType< ::brendan_ur5e::shutdown_request > {
  static const char* value()
  {
    return "brendan_ur5e/shutdown_request";
  }

  static const char* value(const ::brendan_ur5e::shutdown_request&) { return value(); }
};


// service_traits::MD5Sum< ::brendan_ur5e::shutdown_requestRequest> should match 
// service_traits::MD5Sum< ::brendan_ur5e::shutdown_request > 
template<>
struct MD5Sum< ::brendan_ur5e::shutdown_requestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::brendan_ur5e::shutdown_request >::value();
  }
  static const char* value(const ::brendan_ur5e::shutdown_requestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::brendan_ur5e::shutdown_requestRequest> should match 
// service_traits::DataType< ::brendan_ur5e::shutdown_request > 
template<>
struct DataType< ::brendan_ur5e::shutdown_requestRequest>
{
  static const char* value()
  {
    return DataType< ::brendan_ur5e::shutdown_request >::value();
  }
  static const char* value(const ::brendan_ur5e::shutdown_requestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::brendan_ur5e::shutdown_requestResponse> should match 
// service_traits::MD5Sum< ::brendan_ur5e::shutdown_request > 
template<>
struct MD5Sum< ::brendan_ur5e::shutdown_requestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::brendan_ur5e::shutdown_request >::value();
  }
  static const char* value(const ::brendan_ur5e::shutdown_requestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::brendan_ur5e::shutdown_requestResponse> should match 
// service_traits::DataType< ::brendan_ur5e::shutdown_request > 
template<>
struct DataType< ::brendan_ur5e::shutdown_requestResponse>
{
  static const char* value()
  {
    return DataType< ::brendan_ur5e::shutdown_request >::value();
  }
  static const char* value(const ::brendan_ur5e::shutdown_requestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BRENDAN_UR5E_MESSAGE_SHUTDOWN_REQUEST_H
